[package]
name = "market-stimulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bracket-lib="0.8.1"
# tokio = {version = "1",feature = ["full"]}